feign:
  client:
    config:
      front-internal:
        connectTimeout: 2000
        readTimeout: 2000
        decode404: false
        loggerLevel: full

coupon:
  client-url: https://www.coupon-client-url.com
