build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'SarifOutputReport'
    - 'MdOutputReport'

formatting:
  Wrapping:
    maxLineLength: 200
  ArgumentListWrapping:
    indentSize: 4
    maxLineLength: 200
  MaximumLineLength:
    maxLineLength: 200
    ignoreBackTickedIdentifier: true
  ParameterListWrapping:
    maxLineLength: 200
  PropertyWrapping:
    active: false
  Filename:
    active: false
  Indentation:
    indentSize: 4
  PackageName:
    active: false
  SpacingAroundColon:
    active: false
  SpacingAroundCurly:
    active: false

naming:
  active: true
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are)'
  MatchingDeclarationName:
    mustBeFirst: true
  InvalidPackageDeclaration:
    active: true
  PackageNaming:
    active: false
  ConstructorParameterNaming:
    parameterPattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'


style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 200
  UnnecessaryAbstractClass:
    active: true
  UnusedImports:
    active: true
  ReturnCount:
    active: false
  UnusedPrivateMember:
    active: true


exceptions:
  TooGenericExceptionCaught:
    active: false

complexity:
  LongParameterList:
    active: true
    constructorThreshold: 50
    functionThreshold: 50
  TooManyFunctions:
    thresholdInFiles: 20

performance:
  SpreadOperator:
    active: false
